FROM node:16-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --loglevel=error --legacy-peer-deps
COPY . .
EXPOSE 3000
ENV NODE_OPTIONS="--no-warnings"
ENV CHOKIDAR_USEPOLLING=true
CMD [ "npm", "start"]